# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8a7ecdd4f776e8cfb3d2e461a974274fc8da2b653ced9b4bb28692d8e22f71357bd66c52776bb527bdf515939a1bfde94763b8e879f3e9088d1669077df865f

test:
  secret_key_base: 84f91a3476f2a74ae3c17482a94a101572ca139906c7fd75afbeb720ecacf38b20bf06b91b5123f2818cd149962bd5ab5772aa21dd61de460777195677e275f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
